export const AUTH_ERROR_CODES = {
    DUPLICATED_USER_NAME: 'DUPLICATED_USER_NAME',
    DUPLICATED_USER_EMAIL: 'DUPLICATED_USER_EMAIL',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
};
